import os

# API keys for Coinbase Advanced Trade (optional — only needed for private endpoints).
API_KEY    = os.getenv("COINBASE_API_KEY", "")
API_SECRET = os.getenv("COINBASE_API_SECRET", "")

# Exchange and primary symbol
EXCHANGE = "coinbaseadvanced"
SYMBOL   = "BTC/USDT"

SYMBOLS = [
    "BTC/USDT",  "ETH/USDT",  "DOGE/USDT", "ADA/USDT",  "SOL/USDT",
    "LINK/USDT", "HBAR/USDT", "XRP/USDT",  "AVAX/USDT", "DOT/USDT",
    "POL/USDC",  "SUI/USDC",  "SEI/USDC",
]

RSI_BUY_MAX  = 38
RSI_SELL_MIN = 62

STOP_LOSS_PCT   = 1.5
TAKE_PROFIT_PCT = 3.0

MTF_NORMAL_CONFIRM     = 2
MTF_CAUTIOUS_CONFIRM   = 3
CONSECUTIVE_LOSS_CAUTION = 2
CONSECUTIVE_LOSS_PAUSE   = 4
AUTO_PAUSE_DURATION      = 7200

CHECK_INTERVAL           = 20
DEFENSIVE_CHECK_INTERVAL = 60

CONSECUTIVE_SL_LIMIT = 3

EVAL_DELAY       = 3600
COOLDOWN_MINUTES = 30

DAILY_MAX_TRADES = 5
DAILY_LOSS_LIMIT = -5.0

MIN_SIGNALS_FOR_ADJUSTMENT = 3
STATE_FILE   = "config.json"
HISTORY_FILE = "trade_history.json"
